# Generated by Django 2.2.6 on 2020-05-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200508_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='publisher',
            field=models.CharField(default='Anonymous Publisher', max_length=70),
            preserve_default=False,
        ),
    ]
