# Generated by Django 2.2.6 on 2020-05-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='publisher',
            field=models.CharField(default='Anonymous Publisher', max_length=70),
        ),
    ]
