# Generated by Django 2.2.6 on 2020-05-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200527_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='publisher',
            field=models.CharField(blank=True, default='Anonymous Publisher', max_length=70),
        ),
    ]
