# Generated by Django 2.2.6 on 2020-05-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200527_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='publisher',
        ),
    ]
