# Generated by Django 2.2.6 on 2020-06-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_createpoll'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpoll',
            name='publisher',
            field=models.CharField(default='Default publisher', max_length=200),
            preserve_default=False,
        ),
    ]
