# Generated by Django 2.2.6 on 2020-06-13 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_remove_createpoll_publisher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreatePoll',
        ),
    ]
